CREATE TABLE SNS (
	M_ID VARCHAR2(10 CHAR) PRIMARY KEY,
	M_PW VARCHAR2(10 CHAR) NOT NULL,
	M_NAME VARCHAR2(10 CHAR) NOT NULL,
	M_PHONE VARCHAR2(11 CHAR) NOT NULL,
	M_BIRTHDAY DATE NOT NULL,
	M_PHOTO VARCHAR2(200 CHAR) NOT NULL
);

SELECT * FROM SNS;
-------------------------------------------------------------




