-- 요식업 프렌차이즈

-- 홍콩반점 강서점은 홍길동이 운영하고 100석
-- 홍콩반점 종로점은 김길동이 운영하고 80석
-- 한신포차 강남점은 홍길동이 운영하고 150석
-- 부천포차 부천점은 최길동이 운영하고 130석
CREATE TABLE FRANCHISE(
	F_NO NUMBER(3) PRIMARY KEY,		-- 식당 번호
	F_NAME VARCHAR2(10 CHAR) NOT NULL,
	F_LOCATION VARCHAR2(10 CHAR) NOT NULL,
	F_CEO NUMBER(3) NOT NULL,		-- 사장님 번호
	F_SEAT NUMBER(3) NOT NULL
);

CREATE SEQUENCE FRANCHISE_SEQ;

INSERT INTO FRANCHISE VALUES(FRANCHISE.NEXTVAL, '홍콩반점', '강서', 1, 100);
INSERT INTO FRANCHISE VALUES(FRANCHISE.NEXTVAL, '홍콩반점', '종로', 2, 80);
INSERT INTO FRANCHISE VALUES(FRANCHISE.NEXTVAL, '한신포차', '강남', 3, 150);
INSERT INTO FRANCHISE VALUES(FRANCHISE.NEXTVAL, '부천포차', '부천', 4, 130);
------------------------------------------------------------------------------------------------------------
-- 홍길동, 1990-03-01일생, 남자
-- 김길동, 1992-02-01일생, 여자
-- 홍길동, 1991-12-12일생, 여자
-- 최길동, 1989-09-01일생, 남자
CREATE TABLE CEO(
	C_NO NUMBER(3) PRIMARY KEY,		-- 사장님 번호
	C_NAME VARCHAR2(10 CHAR) NOT NULL,
	C_BIRTHDAY DATE NOT NULL,
	C_GENDER CHAR(2 CHAR) NOT NULL
);

CREATE SEQUENCE CEO_SEQ;

INSERT INTO CEO VALUES(CEO_SEQ.NEXTVAL, '홍길동', TO_DATE('1990-03-01', 'YYYY-MM-DD'), '남자');
INSERT INTO CEO VALUES(CEO_SEQ.NEXTVAL, '김길동', TO_DATE('1992-02-01', 'YYYY-MM-DD'), '여자');
INSERT INTO CEO VALUES(CEO_SEQ.NEXTVAL, '홍길동', TO_DATE('1991-12-12', 'YYYY-MM-DD'), '여자');
INSERT INTO CEO VALUES(CEO_SEQ.NEXTVAL, '최길동', TO_DATE('1989-09-01', 'YYYY-MM-DD'), '남자');
------------------------------------------------------------------------------------------------------------
-- 짜장면, 5000원, 홍콩반점 강서점에서 파는
-- 불닭발, 12000원, 한신포차 강남점
--		... 매장당 메뉴 5개정도 !
CREATE TABLE MENU(
	M_NO NUMBER(2) PRIMARY KEY,		-- 메뉴 번호
	M_NAME VARCHAR2(10 CHAR) NOT NULL,
	M_PRICE NUMBER(5) NOT NULL,
	M_F_NO NUMBER(3) NOT NULL		-- 메뉴파는 식당 번호
);

CREATE SEQUENCE MENU_SEQ;

INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '짜장면', 5000, 1);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '짜장밥', 5500, 1);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '볶음밥', 7000, 1);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '유산슬', 20000, 1);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '멘보샤', 14000, 1);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '짜장밥', 6000, 2);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '짬뽕밥', 8000, 2);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '차돌짬뽕', 10000, 2);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '고추잡채', 17000, 2);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '삼선짜장', 13000, 2);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '불닭발', 12000, 3);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '계란찜', 6000, 3);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '모래집', 10000, 3);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '문어발', 4000, 3);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '해물떡볶이', 16000, 3);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '제육볶음', 12000, 4);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '어묵탕', 10000, 4);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '콘치즈', 5000, 4);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '오징어땅콩', 8000, 4);
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '한치', 9000, 4);
------------------------------------------------------------------------------------------------------------
-- 좌석 수 제일 많은 식당 운영하는 사람의 전체 정보 조회
SELECT
	FROM CEO
	WHERE C_NO IN (
		SELECT F_CEO
		FROM FRANCHISE
		WHERE F_SEAT IN (
			SELECT MAX(F_SEAT)
			FROM FRANCHISE
		)
	);

-- 프랜차이즈 메뉴 전체의 이름, 가격
--		을 가격 오름차순 -> 가격이 같다면 메뉴명을 가나다 역순 정렬
-- 여러번 정렬하고 싶을 때... => ORDER BY 컬럼명 (ASC / DESC), 컬럼명 (ASC / DESC), ...
SELECT M_NAME, M_PRICE
	FROM MENU
	ORDER BY M_PRICE ASC, M_PRICE DESC;

-- 전체 사장님들 이름, 생일 조회
SELECT C_NAME, C_BIRTHDAY FROM CEO;

-- 프랜차이즈 식당 몇 개 ?
SELECT COUNT(*) FROM FRANCHISE;

-- 프랜차이즈 메뉴 전체의 평균가 ?
SELECT AVG(M_PRICE) FROM MENU;

------------------------------------------------------------------------------------------------------------
-- 내가 한거
CREATE TABLE PEOPLE(
    P_NO NUMBER(2) PRIMARY KEY,
    P_NAME VARCHAR2(10 CHAR) NOT NULL,
    P_BIRTH DATE NOT NULL,
    P_GENDER VARCHAR2(2 CHAR) NOT NULL
);

CREATE SEQUENCE PEOPLE_SEQ;

CREATE TABLE RESTUARANT(
    R_NO NUMBER(2) NOT NULL,
    R_NAME VARCHAR2(10 CHAR) PRIMARY KEY,
    R_OWNER VARCHAR2(10 CHAR) NOT NULL,
    R_SEAT NUMBER(3) NOT NULL,
        CONSTRAINT FK_OWNER FOREIGN KEY(R_NO)
        REFERENCES PEOPLE(P_NO)
        ON DELETE CASCADE
);

CREATE TABLE MENU(
    M_NO NUMBER(2) PRIMARY KEY,
    M_NAME VARCHAR2(10 CHAR) NOT NULL,
    M_PRICE NUMBER(5) NOT NULL,
    M_RESTUARANT VARCHAR2(10 CHAR) NOT NULL,
        CONSTRAINT FK_NAME FOREIGN KEY(M_RESTUARANT)
        REFERENCES RESTUARANT(R_NAME)
        ON DELETE CASCADE
);

CREATE SEQUENCE MENU_SEQ;

INSERT INTO PEOPLE VALUES(PEOPLE_SEQ.NEXTVAL, '홍길동', TO_DATE('1990-03-01', 'YYYY-MM-DD'), '남자');
INSERT INTO PEOPLE VALUES(PEOPLE_SEQ.NEXTVAL, '김길동', TO_DATE('1992-02-01', 'YYYY-MM-DD'), '여자');
INSERT INTO PEOPLE VALUES(PEOPLE_SEQ.NEXTVAL, '홍길동', TO_DATE('1991-12-12', 'YYYY-MM-DD'), '여자');
INSERT INTO PEOPLE VALUES(PEOPLE_SEQ.NEXTVAL, '최길동', TO_DATE('1989-09-01', 'YYYY-MM-DD'), '남자');
SELECT * FROM PEOPLE;

INSERT INTO RESTUARANT VALUES(1, '홍콩반점 강서점', '홍길동', 100);
INSERT INTO RESTUARANT VALUES(2, '홍콩반점 종로점', '김길동', 80);
INSERT INTO RESTUARANT VALUES(3, '한신포차 강남점', '홍길동', 150);
INSERT INTO RESTUARANT VALUES(4, '부천포차 부천점', '최길동', 130);
SELECT * FROM RESTUARANT;

INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '짜장면', 5000, '홍콩반점 강서점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '짬뽕', 6000, '홍콩반점 강서점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '쟁반짜장', 10000, '홍콩반점 강서점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '볶음밥', 5000, '홍콩반점 강서점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '짬뽕밥', 6000, '홍콩반점 강서점');

INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '짜장면', 5500, '홍콩반점 종로점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '짬뽕', 6500, '홍콩반점 종로점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '쟁반짜장', 9500, '홍콩반점 종로점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '볶음밥', 5500, '홍콩반점 종로점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '짬뽕밥', 6000, '홍콩반점 종로점');

INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '매운오돌뼈', 6000, '한신포차 강남점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '콘치즈불닭', 5000, '한신포차 강남점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '데리야끼마늘똥집', 8000, '한신포차 강남점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '골뱅이 소면', 6500, '한신포차 강남점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '어묵탕', 5500, '한신포차 강남점');

INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '매운오돌뼈', 6500, '부천포차 부천점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '콘치즈불닭', 4500, '부천포차 부천점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '데리야끼마늘똥집', 9000, '부천포차 부천점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '골뱅이 소면', 5500, '부천포차 부천점');
INSERT INTO MENU VALUES(MENU_SEQ.NEXTVAL, '어묵탕', 6500, '부천포차 부천점');
------------------------------------------------------------------------------------------------------------