CREATE TABLE SNS (
	M_ID VARCHAR2(10 CHAR) PRIMARY KEY,
	M_PW VARCHAR2(10 CHAR) NOT NULL,
	M_NAME VARCHAR2(10 CHAR) NOT NULL,
	M_PHONE VARCHAR2(11 CHAR) NOT NULL,
	M_BIRTHDAY DATE NOT NULL,
	M_PHOTO VARCHAR2(200 CHAR) NOT NULL
);

SELECT * FROM SNS;
-------------------------------------------------------------

CREATE TABLE BOARD (
	B_NO NUMBER(3) PRIMARY KEY,
	B_WRITER VARCHAR2(10 CHAR) NOT NULL,
	B_WHEN DATE NOT NULL,
	B_TEXT VARCHAR2(200 CHAR) NOT NULL,
	CONSTRAINT FK_BOARD FOREIGN KEY(B_WRITER)
		REFERENCES SNS(M_ID)
		ON DELETE CASCADE
);

CREATE SEQUENCE BOARD_SEQ;



